version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      # OPTION 1: To use the Local DB below (Good for testing)
      - MONGODB_URI=mongodb+srv://mohamed3rafa01_db_user:eJESM9TXwS8tFt52@calibercluster.erlkuqz.mongodb.net/
            
      - JWT_SECRET=docker_secret_key
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - REDIS_HOST=redis 
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  mongo_data: